### ISSUE TITLE
Put voicemail icon to the notification area

### ISSUE THREAD

**Issue by TellienInTouch** [Sagittarii/sailfishos-lockscreen-voicemail-patch#1]
If you are interested, I made a new branch to put the voicemail notification to the notification area of the lockscreen.

This is a screen shot :

![voicemail](https://cloud.githubusercontent.com/assets/6714994/5882183/6acb84ec-a347-11e4-996b-4a723ce93a9d.jpg)

**Comment by Sagittarii** [comment]
PR accepted
